### ISSUE TITLE
Deprecated calls, build failures

### ISSUE THREAD

**Issue by gczuczy** [batterycenter/embed#5]
Hello,

I've tried now to build my project with the previous fix, however I've got a couple of warnings, then the build failed:
```
[ 20%] Generating _deps/battery-embed-build/embed/autogen/subdir_prayer_txt.cpp
[ 40%] Building CXX object CMakeFiles/foo.dir/_deps/battery-embed-build/embed/autogen/subdir_prayer_txt.cpp.o
[ 60%] Building CXX object CMakeFiles/foo.dir/_deps/battery-embed-build/embed/embed_impl.cpp.o
/home/gczuczy/battery-embed-4/_deps/battery-embed-build/embed/embed_impl.cpp:33:35: warning: 'codecvt_utf8_utf16<wchar_t>' is deprecated [-Wdeprecated-declarations]
        std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
                                  ^
/usr/include/c++/v1/codecvt:541:28: note: 'codecvt_utf8_utf16<wchar_t>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 codecvt_utf8_utf16
                           ^
/usr/include/c++/v1/__config:808:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
/usr/include/c++/v1/__config:781:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
/home/gczuczy/battery-embed-4/_deps/battery-embed-build/embed/embed_impl.cpp:33:14: warning: 'wstring_convert<std::codecvt_utf8_utf16<wchar_t>>' is deprecated [-Wdeprecated-declarations]
        std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> converter;
             ^
/usr/include/c++/v1/locale:3603:28: note: 'wstring_convert<std::codecvt_utf8_utf16<wchar_t>>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 wstring_convert
                           ^
/usr/include/c++/v1/__config:808:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
/usr/include/c++/v1/__config:781:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
/home/gczuczy/battery-embed-4/_deps/battery-embed-build/embed/embed_impl.cpp:51:10: error: no type named 'jthread' in namespace 'std'
    std::jthread embeddedFileWatcherThread = std::jthread([](std::stop_token stopToken) {
    ~~~~~^
/home/gczuczy/battery-embed-4/_deps/battery-embed-build/embed/embed_impl.cpp:51:67: error: no type named 'stop_token' in namespace 'std'
    std::jthread embeddedFileWatcherThread = std::jthread([](std::stop_token stopToken) {
                                                             ~~~~~^
/home/gczuczy/battery-embed-4/_deps/battery-embed-build/embed/embed_impl.cpp:51:51: error: no member named 'jthread' in namespace 'std'
    std::jthread embeddedFileWatcherThread = std::jthread([](std::stop_token stopToken) {
                                             ~~~~~^
2 warnings and 3 errors generated.
*** Error code 1

Stop.
make[2]: stopped in /home/gczuczy/battery-embed-4
*** Error code 1

Stop.
make[1]: stopped in /home/gczuczy/battery-embed-4
*** Error code 1

Stop.
make: stopped in /home/gczuczy/battery-embed-4
```

I've reused my previous repo for reproing this: https://github.com/gczuczy/battery-embed-4

Version informations:
```
$ cmake --version; c++ --version; uname -srm
cmake version 3.27.9

CMake suite maintained and supported by Kitware (kitware.com/cmake).
FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
FreeBSD 14.0-STABLE amd64
# cmake --version; c++ --version; uname -srm
cmake version 3.26.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
Target: aarch64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
FreeBSD 14.0-STABLE arm64
```

**Comment by gczuczy** [comment]
Regarding jthread, according to this, I need a flag in clang, but for some reason it's still not enabling the feature: https://libcxx.llvm.org/Status/Cxx20.html#note-p0660

**Comment by gczuczy** [comment]
I think I could just disable this part using `B_PRODUCTION_MODE`, I'm including SQL schemas, so there's no point in updating them runtime.

Also, I've found there's the `__cpp_lib_jthread` macro indicating the availability of the feature. I think it would be a good idea to use this, and optionally print a compile-time warning regarding the forceful disable of the feature due to the lack of jthread. I think that would be the graceful way of handling this.

**Comment by gczuczy** [comment]
Another interesting thing, if I put the `b_embed` in a subdir's `CMakeFiles.txt`, it's unable to find the target for it:
```
$ cmake --fresh . && gmake
-- The CXX compiler identification is Clang 16.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Enabling IPO/LTO
-- Configuring done (2.4s)
-- Generating done (0.0s)
-- Build files have been written to: /home/gczuczy/battery-embed-4
[ 25%] Building CXX object CMakeFiles/foo.dir/subdir/foo.cc.o
gmake[2]: *** No rule to make target '_deps/battery-embed-build/embed/autogen/prayer_txt.cpp', needed by 'CMakeFiles/foo.dir/_deps/battery-embed-build/embed/autogen/prayer_txt.cpp.o'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/foo.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```
If I move it to the root CMakeLists.txt, it's all good.

**Comment by HerrNamenlos123** [comment]
Okay, a few things are happening here. Thank you for immediately filing an issue!
First of all, I don't know why you get deprecation warnings, i never had this. (i mean it is deprecated, yeah, but there is not another solution yet, so the consensus is to use it until there is a better solution).
There might be a way to disable that warning for just that few lines, but i can only do that later.

Secondly, all things jthread: You seem to have an old version, in the latest version I already patched that in favor of apple-clang support in Conan, which does not feature std::jthread to this day. I removed jthread and wrote my own std::thread wrapper.
Use the latest version and the std::jthread issue is gone.

And lastly: I also just stumbled upon the issue and I am currently digging into it, why it can't be in a subdirectory. It must have been a negative sideeffect when i cleaned the folder structure to allow for a file to be embedded in multiple targets. However now that you say it works on the same level, but not in a subdirectory, that is a huge help. I am looking into this but don't know the exact reason yet.

**Comment by HerrNamenlos123** [comment]
in the next version the deprecation issue will be gone completely for you because i just realized that the entire function was unnecessarily compiled on all platforms, even though it is only used on Windows. It will no longer be compiled on other platforms in the future.

**Comment by gczuczy** [comment]
True, in the example I forgot to update the tag. In the actual code I updated it to 1.2.12, however now I see a 1.2.13 as well. I apologize for the oversight here, warnings are indeed gone this way.

Compiler might be a bit oldish, right. I just use the one in the base system, as generally it has the feature set I need, and it's frequently getting updated with major OS releases. So far I haven't encountered something I cannot do with it. (Also, due to package optimizations, the systems' package repo is built inhouse, and guess how long does it take for clang-like sutf on rpi4s)

**Comment by HerrNamenlos123** [comment]
No issue with that compiler, it's just strange i haven't run into this issue yet (i have back when i initially wrote the library but completely forgot about it and haven't had it since then).

I am solely in despair, wrestling with CMake currently, not understanding why the most basic thing does not want to work anymore, or wondering why it has even worked until now. I think if it continues this way, I might just keep this as a known issue and tell everyone not to make subdirectories. It just doesn't make any sense. It seems that no matter what i do, CMake does not respect `add_custom_command` if it's not called within the same subdirectory as the target was created in... And there is no way to find out in which directory it was created or if it's different from the current one...

**Comment by gczuczy** [comment]
I'm far from being an expert of cmake, however I'm very happy that we could leave the autohell behind...

**Comment by HerrNamenlos123** [comment]
@gczuczy I was not able to solve the problem directly, but I found a solution. Please take a look at the Readme and examples to see what solution I came up with. After a lot of wrestling with CMake, I actually find it's the best solution, even if it would have worked in the first place.

Regarding the warning: For the life of my, i can't get this warning to reproduce. I tried different clang versions, all warnings enabled, godbolt with the latest clang versions, but no matter what I do i can't get the warning whatsoever. I am going to leave it as is and if it comes up again in the future, feel free to message me. For now you should be good since it can only happen on Windows anymore.

**Comment by gczuczy** [comment]
It's totally awesome, thank you very much :)
