### ISSUE TITLE
std::copy_n is defined in <algorithm>

### ISSUE THREAD

**Issue by kainiederhagen** [batterycenter/embed#7]
Since embed.hpp uses std::copy_n it should include the <algorithm> header as well.

https://en.cppreference.com/w/cpp/algorithm/copy_n

https://github.com/batterycenter/embed/blob/73de31488b64f2eef1eda6ebdda2a893bc87923a/CMakeLists.txt#L181

**Comment by HerrNamenlos123** [comment]
In what Compiler on what Platform does this cause an issue? I will add it but I haven't had an issue with that in all compilers I tested...

**Comment by kainiederhagen** [comment]
It failed under windows with gcc 14.1.0.

Clang under windows seems to be using the msvc std lib, therefore it can find std::copy_n

I'd expect both gcc and clang to fail under linux.

**Comment by 0xFEEDCAFE** [comment]
I can confirm, that the algorithm header is indeed missing and thus the code fails to build on Linux with Clang 15 and GCC 12.3.

**Comment by HerrNamenlos123** [comment]
I just added the header and it should work without issues now

**Comment by kainiederhagen** [comment]
Thank you!
