### ISSUE TITLE
Please update conan status in README.md

### ISSUE THREAD

**Issue by toge** [batterycenter/embed#9]
Thanks a lot for your help in improving the recipe.
Now, battery-embed has been registered in conan-center-index!
https://conan.io/center/recipes/battery-embed?version=1.2.19

It would be appreciated if you could update the status of conan in README.md.

**Comment by HerrNamenlos123** [comment]
Done! Thank you so much for your efforts!

**Comment by toge** [comment]
Thanks a lot!
